### ISSUE TITLE
dataset are not getting downloaded

### ISSUE THREAD

**Issue by TusharVerma2497** [konstantinklemmer/spate-gan#1]
data_utils.py is making requests for the datasets but status404 not found is returned.
Better to post the direct link to the datasets in Readme file

**Comment by konstantinklemmer** [comment]
Hi! Which dataset is the problem? I will check and try to fix that.

**Comment by TusharVerma2497** [comment]
While I only need the Extreme weather dataset to work on, neither of the dataset is being downloaded

train.py script calls the data_util.py script which tries to download "lgcp", "extreme weather" and "turbulent flows" dataset one by one starting with lgcp dataset, here itself the error appears.

>>python train.py 
TRAINING - Dataset: lgcp Emb: spate Loss: cotgan
Traceback (most recent call last):
  File "train.py", line 452, in <module>
    train(args)
  File "train.py", line 35, in train
    dataset, x_height, x_width = fetch_lgcp(time_steps=time_steps)
  File "/scratch/scai/msr/aiy227514/spate-gan/src/data_utils.py", line 92, in fetch_lgcp
    data = np.array(json.load(json_file)).astype(np.float32)
  File "/home/scai/msr/aiy227514/.conda/envs/spategan/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/home/scai/msr/aiy227514/.conda/envs/spategan/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/scai/msr/aiy227514/.conda/envs/spategan/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/scai/msr/aiy227514/.conda/envs/spategan/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)


The downloaded **lgcp.json** contains the following one line only saying error404 not found

<html lang=en><meta charset=utf-8><meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width"><title>Error 404 (Not Found)!!1</title><style nonce="zWzmLtrR48SgHXaSlJ18Yw">*{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{color:#222;text-align:unset;margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px;}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}pre{white-space:pre-wrap;}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}</style><main id="af-error-container" role="main"><a href=//www.google.com><span id=logo aria-label=Google role=img></span></a><p><b>404.</b> <ins>That’s an error.</ins><p>The requested URL was not found on this server. <ins>That’s all we know.</ins></main>

**Comment by konstantinklemmer** [comment]
Quick update: the lgcp and extreme weather dataset were hosted on my personal GDrive and seem to have been deleted when I recently hit some storage limits. I am quite sure I made a backup though and will see if I can host it somewhere else ASAP.

**Comment by TusharVerma2497** [comment]
Thank you!! I highly appreciate that

**Comment by longmengxuan** [comment]
Hello, I am experiencing the same reported error. May I ask if the problem has been solved?
